package com.opencart.admin.dao.model.catalog;

import javax.ws.rs.core.Response;

public interface ModelCatalogCategoryDAO {
  public Response editCategory10();
  public Response getCategoryStores();
  public Response editCategory17();
  public Response repairCategories();
  public Response editCategory18();
  public Response editCategory15();
  public Response editCategory16();
  public Response editCategory13();
  public Response editCategory14();
  public Response editCategory11();
  public Response getCategoryFilters();
  public Response addCategory7();
  public Response addCategory8();
  public Response addCategory3();
  public Response addCategory4();
  public Response addCategory5();
  public Response addCategory6();
  public Response addCategory1();
  public Response getCategoryLayouts();
  public Response addCategory2();
  public Response getCategoryDescriptions();
  public Response repairCategories2();
  public Response repairCategories1();
  public Response repairCategories3();
  public Response getTotalCategoriesByLayoutId();
  public Response editCategory9();
  public Response getCategoryPath(  Integer CategoryId);
  public Response deleteCategory9();
  public Response deleteCategory();
  public Response getTotalCategories();
  public Response deleteCategory5();
  public Response editCategory1();
  public Response deleteCategory6();
  public Response deleteCategory7();
  public Response editCategory3();
  public Response editCategory2();
  public Response editCategory5();
  public Response deleteCategory1();
  public Response deleteCategory2();
  public Response editCategory4();
  public Response editCategory7();
  public Response deleteCategory3();
  public Response deleteCategory4();
  public Response editCategory6();
}